# https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html
spring:
  # ====================================================================================================================
  # = DEVTOOLS
  # ====================================================================================================================
  devtools:
    livereload:
      port: 35730

joinfaces:
  faces:
    project-stage: development

# ======================================================================================================================
# = LOGGING
# ======================================================================================================================
logging:
  level:
    com:
      github:
        computerhuis:
          dco: DEBUG
