#  https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html
spring:
  jmx:
    enabled: false
  main:
    banner-mode: OFF
  lifecycle:
    timeout-per-shutdown-phase: 1s

  # ====================================================================================================================
  # = MULTIPART UPLOAD
  # ====================================================================================================================
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # ====================================================================================================================
  # = DATA SOURCE
  # ====================================================================================================================
  datasource:
    hikari:
      poolName: hikari-pool-dco

  # ====================================================================================================================
  # = JPA
  # ====================================================================================================================
  jpa:
    open-in-view: false
    properties:
      hbm2ddl:
        auto: validate

      # ================================================================================================================
      # = HIBERNATE
      # ================================================================================================================
      hibernate:
        show_sql: false
        use_sql_comments: false
        format_sql: false
        jdbc:
          time_zone: Europe/Amsterdam
          use_get_generated_keys: true
          lob:
            non_contextual_creation: true

  # ====================================================================================================================
  # = WEB
  # ====================================================================================================================
  web:
    locale: nl

  # ====================================================================================================================
  # = THYMELEAF
  # ====================================================================================================================
  thymeleaf:
    prefix: classpath:/views

  # ====================================================================================================================
  # = JACKSON
  # ====================================================================================================================
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: Europe/Amsterdam

  threads:
    virtual:
      enabled: true

# ======================================================================================================================
# = SERVER - INCLUDE AN ERROR MESSAGE JSON
# ======================================================================================================================
server:
  error:
    include-message: always

# ======================================================================================================================
# = LOGGING
# ======================================================================================================================
logging:
  pattern:
    console: '%date [%highlight(%-5level)] [%thread] [%cyan(%logger:%line)] -%mdc{RID} %message%n'
  level:
    root: INFO
    com:
      github:
        computerhuis:
          dco: DEBUG
    org:
      springframework:
        security:
          web:
            csrf: DEBUG
