# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  jmx:
    enabled: false
  main:
    banner-mode: OFF
  lifecycle:
    timeout-per-shutdown-phase: 20s

  # ====================================================================================================================
  # = MULTIPART UPLOAD
  # ====================================================================================================================
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # ====================================================================================================================
  # = Message bundles
  # ====================================================================================================================
  messages:
    encoding: ISO-8859-1
    basename: languages/messages

  # ====================================================================================================================
  # = DATA SOURCE
  # ====================================================================================================================
  datasource:
    jndi-name: jdbc/dco

  # ====================================================================================================================
  # = JPA
  # ====================================================================================================================
  jpa:
    open-in-view: false
    properties:
      hbm2ddl:
        auto: validate

  # ====================================================================================================================
  # = WEB
  # ====================================================================================================================
  web:
    locale: nl

# ======================================================================================================================
# = FACES
# ======================================================================================================================
joinfaces:
  faces:
    project-stage: development
  primefaces:
    theme: saga
    CSP: true
